apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
  namespace: roxene
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      tolerations:
        - key: cloud.google.com/gke-spot
          operator: Equal
          value: "true"
          effect: NoSchedule
